version: '3.1'
services:
    backend:
        image: 'kansimp/koi_farm:latest'
        restart: unless-stopped
        environment:
            - DB_URL=mongodb+srv://root:123@cluster0.wgyusjf.mongodb.net/pethome?retryWrites=true&w=majority&appName=Cluster0
        ports:
            - 5000:5000
